import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
export default {
  // 与首页 HUD DOM 同源（原 Jinja 已迁入 homeHudBody.html）/ Same HUD markup as Vite home app
  content: ["./src/apps/home/homeHudBody.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#131313",
        "surface-tint": "#ffb4a8",
        "secondary-fixed": "#ffdad4",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "inverse-primary": "#c00100",
        outline: "#b18780",
        "tertiary-container": "#ff5541",
        "on-secondary-fixed": "#3e0502",
        "on-error": "#690005",
        "secondary-fixed-dim": "#ffb4a8",
        "on-surface-variant": "#ebbbb4",
        "on-primary-container": "#5c0000",
        "surface-variant": "#353535",
        "inverse-surface": "#e2e2e2",
        "inverse-on-surface": "#303030",
        background: "#131313",
        "surface-container-high": "#2a2a2a",
        secondary: "#ffb4a8",
        "on-surface": "#e2e2e2",
        tertiary: "#ffb4a8",
        "primary-fixed-dim": "#ffb4a8",
        "surface-container-low": "#1b1b1b",
        "surface-bright": "#393939",
        primary: "#ffb4a8",
        "on-primary-fixed-variant": "#930100",
        error: "#ffb4ab",
        "primary-fixed": "#ffdad4",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-container": "#5c0000",
        "secondary-container": "#7b3228",
        "outline-variant": "#603e39",
        "surface-container-highest": "#353535",
        "on-tertiary-fixed-variant": "#930000",
        "tertiary-fixed": "#ffdad4",
        "surface-container": "#1f1f1f",
        "on-secondary-fixed-variant": "#783026",
        "tertiary-fixed-dim": "#ffb4a8",
        "on-secondary": "#5b1a12",
        "on-tertiary": "#690000",
        "surface-dim": "#131313",
        "on-secondary-container": "#ff9f90",
        "primary-container": "#ff5540",
        "on-primary": "#690100",
        "on-background": "#e2e2e2",
        "on-tertiary-fixed": "#410000",
        "on-primary-fixed": "#410000",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
    },
  },
  plugins: [forms, containerQueries],
};
